# Generated by Django 5.0 on 2023-12-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frontIMG',
            field=models.ImageField(upload_to='products'),
        ),
    ]
