# Generated by Django 5.0 on 2023-12-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_product_backimg_product_description_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='backIMG',
            field=models.ImageField(upload_to='static/siteapp/images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frontIMG',
            field=models.ImageField(upload_to='static/siteapp/images/products'),
        ),
    ]
